version: '2'
services:
  db:
    volumes:
      - db-sync:/var/lib/mysql:nocopy

  php:
    volumes:
      - php-www-sync:/var/www/html/:nocopy
      - ${PWD}/auth.json:/tmp/auth.json
        
  webserver:
    volumes:
      - php-www-sync:/var/www/html/:nocopy
      - ${PWD}/config/shop.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/config/fastcgi_params.oxid:/etc/nginx/conf.d/fastcgi_params.oxid
      - ${PWD}/config/upstreams.conf:/etc/nginx/conf.d/upstreams.conf
      - ${PWD}/config/httpd.conf:/usr/local/apache2/conf/httpd.conf

volumes:
  db-sync:
    external: true
  php-www-sync:
    external: true